name: river_raid_game
description: "Flame project that simulates the River Raid game originally developed for the Atari 2600 in 1982."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.5.3 <4.0.0'

dependencies:
  audioplayers: 5.2.1
  flame: ^1.19.0
  flame_texturepacker: ^4.1.0
  flame_tiled: ^1.20.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.1
  flutter_soloud: 2.0.2
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  custom_lint: ^0.6.5
  pyramid_lint: ^2.0.1
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/audio/
    - assets/images/
    - assets/images/atlas/
    - assets/images/spritesheet/
    - assets/images/tiles/
    - assets/tiles/bridge/
    - assets/tiles/hud/
    - assets/tiles/stage_1/
    - assets/tiles/stage_2/
    - assets/tiles/stage_3/
    - assets/tiles/stage_4/
    - assets/tiles/stage_finish_bottom/
    - assets/tiles/stage_finish_top/

  fonts:
    - family: River-Raid-Font
      fonts:
        - asset: 'assets/fonts/River-Raid-Font.ttf'
          weight: 400

flutter_native_splash:
  image: assets/images/splash/splash.png
  color: "#751B1F"
  android_12:
    image: assets/images/splash/splash_android_12.png
  android: true
  android_gravity: center
  ios: true
  ios_content_mode: center
  web: false
  fullscreen: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path_ios: assets/images/icons_launcher/icon_launcher_ios.png
  image_path_android: assets/images/icons_launcher/icon_launcher_android.png
  windows:
    generate: false
  macos:
    generate: false
  web:
    generate: false