name: river_raid_game
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.5.1 <4.0.0'

dependencies:
  flame: ^1.18.0
  flame_texturepacker: ^4.0.1
  flame_tiled: ^1.20.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  custom_lint: ^0.6.4
  pyramid_lint: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/atlas/
    - assets/images/tiles/
    - assets/tiles/stage_1/
    - assets/tiles/stage_2/
    - assets/tiles/stage_3/
    - assets/tiles/stage_4/
